# ----
# Site

repository: akshob/akshob.github.io
title: Recipe Workshop
url: "https://recipeworkshop.in"
baseurl:
analytics_url: https://matomo.recipeworkshop.in
newsletter_action:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Guide to a happy tummy.
author:
  name: Akshob
  email: info@akshob.in
  twitter: akshobg
social:
  name: Recipe Workshop
  links:
    - https://github.com/akshob/recipeworkshop

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

collections:
  articles:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-liquify

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - [vendor]

social_icons:
  - Facebook
  - Google Plus
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - Email
  - RSS

_options:
  author_image:
    width: 400
    height: 400